### ISSUE TITLE
about regex test case

### ISSUE THREAD

**Issue by ivan19871002** [SamirTalwar/smoke#109]
example
I add  daytime into  os-release , like  OS-VERSION=GITHUB-20230320-AAAA

my test cast 

```
command:
  - sh

tests:
  - name: bsp version check
    command: |
      day=20230320
      cat /etc/os-release
    stdout:
      matches: 
        OS-VERSION=.*${day}.*
```

it is  failed:smoke: ParseError {errError = ICUError U_REGEX_BAD_INTERVAL, errLine = Just 1, errOffset = Just 20}

if change ${day} to  20230320, it is success
```
command:
  - sh

tests:
  - name: bsp version check
    command: |
      day=20230320
      cat /etc/os-release
    stdout:
      matches: 
        OS-VERSION=.*20230320.*

```

so , If i want use parm for day , How should I write stdout?
