### ISSUE TITLE
How to assert part of a string

### ISSUE THREAD

**Issue by wolframkriesing** [SamirTalwar/smoke#36]
I would love to do something like this

```
tests:
  - name: ...
    stdout:
      contains: |
        12345
```

Currently, I had not found a way to assert for part of the string. In the docs I only saw how to match all of stdout.

PS: what is the `|` at the end of `contains: |`, is this yaml standard? You use it in many places but I didnt find an explanation. Thanks
