### ISSUE TITLE
Support for glob expressions or another way to run the same kind of test on many files

### ISSUE THREAD

**Issue by SamirTalwar** [SamirTalwar/smoke#39]
One use case for Smoke is to simply provide many different potential input and output files, and compare them. However, it gets old doing the following:

```yaml
tests:
  - name: thing 1
    stdin:
      file: thing1.in
    stdout:
      file: thing1.out

  - name: thing 2
    stdin:
      file: thing2.in
    stdout:
      file: thing2.out

  - name: thing 3
    stdin:
      file: thing3.in
    stdout:
      file: thing3.out

# ...
```

Not only is it monotonous, but error-prone.

@jaspervdj suggested finding a better way to avoid this repetition, just like [goldplate](https://github.com/fugue/goldplate) does.

**Comment by SamirTalwar** [comment]
Perhaps we could do something like this:

```yaml
tests:
  - name: %
    stdin:
      file: *.in
    stdout:
      file: %.out
```

This would detect the glob expression in `stdin.file`, and expand it to the long form above, using `%` as the placeholder for the pattern matched by `*`.
