### ISSUE TITLE
--bless adds Windows newlines in binary files

### ISSUE THREAD

**Issue by codecop** [SamirTalwar/smoke#61]
Hi Samir, hope you are doing well. I am using latest Smoke to test some command line tools. Some tools create binary output, e.g. BMP images. In these situations,

```
  - name: "XCOLOR"
    command: "..\\bin\\XCOLOR 80x25x256.bmp test.out 0 1"
    files:
      - path: test.out
        contents:
          file: xcolor.bmp

```
the xcolor.bmp had 0d added before all 0a bytes. I am using Windows. I guess it is something of the fwrite/C function or mode of file you use. Or maybe we need a switch to indicate binary files?
